:memo: update: add Discord contribution directive in CONTRIBUTING.md
Pinqo-community/equilibre-pwa pull request #4
Opened 2024-10-09 12:09 UTC by loumorganrene

Proposition of updates to the CONTRIBUTING.md

https://github.com/Pinqo-community/mental-health-app/issues/3

2024-10-09 12:17 UTC, BenjaminSiret commented on CONTRIBUTING.md
> +1. **Clone the Repository**: Since we're a small team, all contributors are added directly to the main repository, so there's no need to fork it.
J'aimerai bien qu'on en discute, car l'idée de contributeurs externes qui utiliseraient le fork me semble adéquat.

2024-10-09 12:23 UTC, BenjaminSiret commented on CONTRIBUTING.md
> +2. **Code Review**: Your PR will be reviewed by one or more team members. Be open to feedback and make any necessary changes. Once approved, your PR will be merged into the `develop` branch.
Nous avons convenu qu'on partait sur 2 reviewers pour les PR, on peut aussi en discuter sans problème si il faut revenir sur ce choix.

2024-10-09 13:25 UTC, gmagnenat commented on CONTRIBUTING.md
> +1. **Clone the Repository**: Since we're a small team, all contributors are added directly to the main repository, so there's no need to fork it.
J'aime aussi les deux options, on reste ouvert et ça couvre les deux cas d'utilisation.

2024-10-09 13:27 UTC, gmagnenat commented on CONTRIBUTING.md
> +2. **Code Review**: Your PR will be reviewed by one or more team members. Be open to feedback and make any necessary changes. Once approved, your PR will be merged into the `develop` branch.
Après reflection 2 c'est peut-être trop, dans l'idée c'était pour encourager les membres à plus d'interaction dans les code reviews.

2024-10-09 13:53 UTC, dev-paulL commented on CONTRIBUTING.md
> +2. **Code Review**: Your PR will be reviewed by one or more team members. Be open to feedback and make any necessary changes. Once approved, your PR will be merged into the `develop` branch.
Ca depend, 2 reviews ça peut etre bien pratique selon la PR, notamment pour ce qui est actions et autres, pour les débuts et la phase rédaction des readme 1 peut suffire

2024-10-09 14:34 UTC, loumorganrene commented on CONTRIBUTING.md
> +2. **Code Review**: Your PR will be reviewed by one or more team members. Be open to feedback and make any necessary changes. Once approved, your PR will be merged into the `develop` branch.
Deux ça me parait bien aussi.

2024-10-09 14:39 UTC, BenjaminSiret commented on CONTRIBUTING.md
> +1. **Clone the Repository**: Since we're a small team, all contributors are added directly to the main repository, so there's no need to fork it.
Dans les directives de Gwen je pense qu'il parlait plus de notre equipe restreinte, et du coup laisser la possibilité de fork pour les personnes exterieures (mais j'ai peut etre mal compris)

2024-10-09 14:40 UTC, gmagnenat commented on CONTRIBUTING.md
> +1. **Clone the Repository**: Since we're a small team, all contributors are added directly to the main repository, so there's no need to fork it.
Ah ! je comprends mieux du coup. Je cherchais un lien avec Discord dans tes modifications. 
En fait le contenu posté sur discord date de avant ce fichier, je l'ai fait ensuite basé sur mes notes.

2024-10-09 14:41 UTC, gmagnenat commented on CONTRIBUTING.md
> +1. **Clone the Repository**: Since we're a small team, all contributors are added directly to the main repository, so there's no need to fork it.
@loumorganrene désolé pour la confusion

2024-10-09 14:54 UTC, loumorganrene commented on CONTRIBUTING.md
> +1. **Clone the Repository**: Since we're a small team, all contributors are added directly to the main repository, so there's no need to fork it.
Pas de soucis ! Je comprend mieux aussi.
Je repasse sur la version précédente du coup.

2024-10-09 15:02 UTC, loumorganrene commented
> Un autre détail mais en suivant les principes de conventional commits, ton commit devrait plutôt se nommer : `docs: update Discord contribution directive in CONTRIBUTING.md`

C'est bien noté, par contre j'ai l'habitude d'utiliser les gitmoji pour visualiser très vite la nature d'un commit, est-ce que vous préférez qu'on ne les utilise pas sur ce projet pour garder de la cohérence visuelle dans les messages de commit ?

Je demande avant de reword mon commit du coup !

2024-10-09 17:21 UTC, gmagnenat commented
@loumorganrene pour donner mon avis, je suis assez pour l'organisation textuelle ça facilite le classement, la recherche et l'organisation. Mais si tu veux ajouter en plus un emoji libre à toi, je vois pas le problème :)

2024-10-09 19:01 UTC, loumorganrene commented
@gmagnenat 
> pour donner mon avis, je suis assez pour l'organisation textuelle ça facilite le classement, la recherche et l'organisation. Mais si tu veux ajouter en plus un emoji libre à toi, je vois pas le problème :)

Boarf ! Si vous suivez pas la convention gitmoji, je préfère la cohérence et faire du textuel 😊

2024-10-10 20:17 UTC, gmagnenat requested changes

2024-10-10 20:17 UTC, gmagnenat commented on CONTRIBUTING.md
> +git commit -m "feat(feature-name): Add a brief description of your changes"
Je garderai cette partie plus généraliste au lieu d'un exemple. Ou alors tu peux ajouter plusieurs exemples différents pour apporter une clarté sur la convention de commit?

2024-10-11 11:02 UTC, loumorganrene commented on CONTRIBUTING.md
> +git commit -m "feat(feature-name): Add a brief description of your changes"
Je m'étais posé la question avant de faire le changement, au final, vu que j'ai rajouté avant un appel à suivre les préfixes de commit conventionnel, je me dis que retourner sur l'exemple générique va très bien.
C'est corrigé et push.

2024-10-11 11:14 UTC, gmagnenat approved these changes
Tout bon pour moi 🚀

2024-10-11 11:14 UTC, merged